# Generated by Django 3.2.9 on 2021-11-27 08:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productSku', models.CharField(default='', max_length=255)),
                ('productDescription', models.CharField(default='', max_length=255)),
                ('quantity', models.IntegerField()),
                ('dateAdded', models.DateTimeField(default=datetime.datetime(2021, 11, 27, 19, 42, 51, 785596))),
                ('location', models.CharField(max_length=255)),
            ],
        ),
    ]
