# Generated by Django 3.2.6 on 2021-11-28 12:53

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='dateAdded',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 28, 12, 53, 30, 899197, tzinfo=utc)),
        ),
    ]
