# Generated by Django 3.2.6 on 2021-11-30 23:43

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20211201_1042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='dateAdded',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 30, 23, 43, 15, 866933, tzinfo=utc)),
        ),
    ]
